# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 23:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_exc_api', '0002_stockexchangeindex_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='stockexchangeindex',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_exc_api.Country'),
        ),
    ]
