# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 00:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_exc_api', '0003_auto_20160319_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historical_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, default=0.0)),
                ('high_price', models.FloatField(blank=True, default=0.0)),
                ('low_price', models.FloatField(blank=True, default=0.0)),
                ('volume', models.FloatField(blank=True, default=0.0)),
                ('change_percent', models.FloatField(blank=True, default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='stockexchangeindex',
            name='change',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockexchangeindex',
            name='change_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockexchangeindex',
            name='prev_close',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockexchangeindex',
            name='volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockexchangeindex',
            name='hist_data',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.CASCADE, to='stock_exc_api.Historical_Data'),
            preserve_default=False,
        ),
    ]
