# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_exc_api', '0004_auto_20160320_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historical_data',
            name='change_percent',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='historical_data',
            name='high_price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='historical_data',
            name='low_price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='historical_data',
            name='value',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='historical_data',
            name='volume',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
