# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 00:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_exc_api', '0005_auto_20160320_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockexchangeindex',
            name='hist_data',
        ),
    ]
