# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 00:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_exc_api', '0007_auto_20160320_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockexchangeindex',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock_exc_api.Country'),
        ),
    ]
