# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_exc_api', '0010_auto_20160320_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockexchangeindex',
            name='change',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockexchangeindex',
            name='change_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockexchangeindex',
            name='prev_close',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockexchangeindex',
            name='volume',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
