# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_exc_api', '0011_auto_20160320_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockexchangeindex',
            name='hist_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock_exc_api.Historical_Data'),
        ),
    ]
