# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 01:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_exc_api', '0012_stockexchangeindex_hist_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('code', models.CharField(blank=True, default='', max_length=100)),
                ('value', models.FloatField(blank=True, null=True)),
                ('prev_close', models.FloatField(blank=True, null=True)),
                ('change', models.FloatField(blank=True, null=True)),
                ('change_percent', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock_exc_api.Country')),
            ],
        ),
        migrations.AddField(
            model_name='stockexchangeindex',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock_exc_api.Company'),
        ),
    ]
