# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_exc_api', '0013_auto_20160320_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockexchangeindex',
            name='company',
        ),
        migrations.RemoveField(
            model_name='stockexchangeindex',
            name='hist_data',
        ),
        migrations.AddField(
            model_name='company',
            name='index',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock_exc_api.StockExchangeIndex'),
        ),
        migrations.AddField(
            model_name='historical_data',
            name='index',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock_exc_api.StockExchangeIndex'),
        ),
    ]
