# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_exc_api', '0015_auto_20160320_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historical_data',
            name='value',
            field=models.FloatField(blank=True, default='', null=True),
        ),
    ]
