# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_exc_api', '0020_auto_20160324_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historical_data',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
