# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_exc_api', '0021_auto_20160324_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historical_data',
            old_name='value',
            new_name='hist_value',
        ),
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='historical_data',
            name='change_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historical_data',
            name='high_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historical_data',
            name='low_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historical_data',
            name='volume',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
