# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_exc_api', '0023_auto_20160324_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historical_data',
            options={'ordering': ['hist_value']},
        ),
        migrations.AlterUniqueTogether(
            name='historical_data',
            unique_together=set([('index', 'hist_value')]),
        ),
    ]
