# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_exc_api', '0024_auto_20160324_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
