# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_exc_api', '0025_auto_20160326_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
